sudo: required

language: java

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

env:
  global:
  # ARTIFACTORY_USERNAME
  - secure: "m6/oDXovHoe9eJf9j9PGJ7Qyk9Ol5Emjuy7T/C5y3bXHMdnHbqhb8qWgt/IRFKeEIwaU9hacKPbwtycQdptNfSpp235WKtoqJshpQs+NKNvAGoEmymCNvZvp8Y6uU9dep3pyzQO/CnJFW2rp3FYykqkrG8SeHUTviHRLwWb8zm/3msWbf7pLIgyvfnrmDcHAgxZMqbVJvBrIZKMXDJUzFEulKIp0hCyrzveTAstPU5mmyTJTl1IFe09c5f2y49khkbAJUW4N8OErzaEC+3V/3dUhh1lTk7wTiqQ4NRHkmUl2yXY4L2wdP5cD2fnTRxKyYacSV5edum43QD5a7+mNKRKnpuEwCWmJMjd6LrlA4ijxHRyUWirukeuF+Aa87j18CY3LTZGlMURtUQ3VNV6SR5Ns7L3Kl7ONIRbgp/jvsqTe4kzTtsl4GZFeAbrfjP75NSTJ6OkksrbUXSjHvaD349QIi+i6D5BQz7khKa13SVAZdBlw1d3rk/9iQGmGk7aJJhMm8OcTJYDmjz0/nwdi2nzfrwDub9QDq6qijadwleGe4gBXaAKO5YFdWkMogD7j8+ZJaV1Q/TiYOERYoJhILXjYtTWq69IYFO10g0vJWIhrH6B95O/Y4n7OopeevVo3YZ7ZdwkdxozczwbBnVJrwonethL0yEmfXsOFNoG37js="
  # ARTIFACTORY_PASSWORD
  - secure: "eCPOIKutjqwtCM9KtbrgRlJEdMfPP6YSJW9ZsE/656KuYEp34g3Ta/hH5JSp78My02aRF93al2rRP36romsB6Q5A03RbTWoOEU8pmID7QkFZWpjUOG8WViXG5ujxa/vrtTvkVwdZjjeTaGG7/tATg34vXllHxsdMYMVKdtXMLNP0H9rmBerc2Fvc+IwPBw26s48K71OIkLk1j/q4CjuDb/0tIqGZzevkqhw4ucbf9eBOtRdv6GisE0YgaunD/tltmGVlwdXhDBZrb47hC8pFSYU8vxKKLE5FkCkFPwEgAPal9Bgc5hDgvEBrx/Fza7Kbl12sIxKdXp+lHGeFMd/WT6hcjdT7a6kCKP7OiD8JoPKxQQK1U44N8GM+eYZJWU7Jl0kDtzUHuhFiu9hz5IglV1MoZjylYVx6S5O+SEOgYjviYKofTiJTa0bKoW0Om2Kvc6ilmIgNg1IVtqBmalZD2t/SULQPfKzwekmLctRlKpnY/pV+fsKf9matAl6qlhmmbkQosZT/OUMMBXC5nnK/g3C2rp6HI1fEt7r9jqWarDnF8nzPWOnT5gmL39OYvRz70qWlqISFPMa3+DAfPdeqAdWRDdgJdSC/QrxKPpdSchuT8uT4DWFk9peQGKxYPtNNdRs2KkhgxfYvgwCKNhIAideqQVBDSCI3uIZt4iLnjns="
install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh

script:
- mvn clean install

deploy:
- provider: script
  script: "mvn deploy -DskipTests --settings ci-tools/common/maven-settings.xml"
  skip_cleanup: true
  on:
    branch: master
